database:
  host: localhost
  port: 3306
  name: parkour
  user: parkour
  password: password

reset_location:
  world: world
  x: 0.5
  y: 63
  z: 0.5
  yaw: -90
  pitch: 0

messages:
  start: "&aParkour Started!"
  complete: "&bYou completed the Parkour in &e{time}&b!"
  actionbar: "&eTime: &f{time}"
  reset: "&cYour parkour progress has been reset!"
  cancel: "&eYour parkour timer has been cancelled!"
  timeout: "&cYou took too long!"
  personal_best: "&6&lğŸ† NEW PERSONAL BEST!"

max_time: 300 #5 minutes (300 secs) by default

debug: false